In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [2]:
from _src import PublicAnalysis,\
                    Calculator

file_path = "data/apt_1.xlsx"
anal = PublicAnalysis(file_path)

## 데이터 소개
- 해당 데이터는 108가구의 1년치 월 별 사용량 데이터를 가지고 있는 데이터이다.
- 이 중, 1월달 데이터를 이용하여 공용부의 전기요금 구성요소들의 특징을 살펴보도록 한다.

In [3]:
anal.set_init()
anal.meter_year.iloc[:, :10]

아파트1-104-1206  아파트1-104-303  아파트1-104-1307  아파트1-104-1208  아파트1-104-408  \
1              99            10             23             40            39   
2              94            77             18            135            30   
3              96            77             20            169            28   
4              75            76             30            127            58   
5             165           150            161              7            75   
6             186           148            108              6            48   
7             292           136            273              6            52   
8             311             7            240              6            49   
9             173             7             98              6            41   
10            149             7             30              8            35   
11             21             2              0              7            17   
12             21             2             24             16            41   

    아파트1-104-203  아파트1-103-1402  아파트1-103-402  아파트1-103-1201  아파트1-103-801  
1            197            218           228             84           223  
2            192            201           230            154           188  
3            216            231           241            247           232  
4            217            226           232            250           209  
5            164            216           224            200           189  
6            182            211           225            192           192  
7            247            375           306            253           287  
8            318            390           345            271           319  
9            231            214           239            183           193  
10           200            202           209            193           224  
11           197            209           178            190           210  
12           178            232           190            186           218

In [4]:
anal.select_month() # Default Value : 1
anal.meter_month.iloc[:5]

name usage (kWh)
0  아파트1-104-1206          99
1   아파트1-104-303          10
2  아파트1-104-1307          23
3  아파트1-104-1208          40
4   아파트1-104-408          39

In [5]:
calc = Calculator(anal.meter_month, 
                  month=1,
                  contract="단일")\
                    .set_households()

## 기본요금

In [10]:
for idx in range(0, 100):
    print(calc.households[idx].kwh, calc.households[idx].elec_bill)

99 5713.0
10 1000
23 1000
40 1254.0
39 1177.0
197 13123.0
218 18982.0
228 20428.0
84 4580.0
223 19704.0
236 21584.0
387 43420.0
222 19560.0
397 44866.0
319 33586.0
711 116311.0
251 23754.0
326 34598.0
255 24332.0
257 24622.0
424 55209.0
156 10022.0
228 20428.0
350 38070.0
253 24042.0
239 22018.0
129 7981.0
345 37346.0
376 41828.0
238 21874.0
380 42408.0
267 26068.0
219 19126.0
183 12063.0
297 30406.0
473 65640.0
322 34020.0
309 32140.0
416 53505.0
262 25344.0
285 28670.0
240 22164.0
237 21730.0
406 51376.0
280 27948.0
291 29538.0
386 43274.0
233 21150.0
331 35322.0
222 19560.0
284 28526.0
405 51164.0
420 54358.0
254 24188.0
341 36768.0
257 24622.0
169 11005.0
214 18404.0
298 30550.0
351 38214.0
381 42552.0
263 25488.0
498 70963.0
371 41106.0
369 40816.0
371 41106.0
214 18404.0
111 6621.0
184 12140.0
148 9418.0
151 9645.0
181 11913.0
290 29394.0
180 11838.0
20 1000
176 11534.0
220 19272.0
308 31996.0
181 11913.0
203 16812.0
494 70112.0
436 57763.0
264 25634.0
280 27948.0
463 63511.0
324

In [19]:
calc.households[10].kwh

236

In [111]:
import numpy as np
import sys

STEP_LIMITS = dict({
    "기타": np.array([200, 
                    200, # 400
                   ]),
    "여름": np.array([300, 
                    150 # 450
                   ])
})

In [112]:
# index = 0 10 80

In [119]:
kwh = calc.datas['usage (kWh)'][0]
# print(kwh_1)
# 원하는 결과물 [99, 0, 0]
result = np.zeros(STEP_LIMITS['기타'].size + 1)
step = 0

while kwh > 0:
    if step == 2:
        result[step] = kwh
        break
    else:
        err = kwh - STEP_LIMITS['기타'][step]
        if err < 0:
            result_1[step] = kwh
            kwh_1 -= kwh_1
        else:
            result_1[step] = STEP_LIMITS['기타'][step]
            kwh_1 -= STEP_LIMITS['기타'][step]
    print(result_1)
    step += 1
    
result_1

-101
[99.  0.  0.]


array([99.,  0.,  0.])

In [89]:
kwh_2 = calc.datas['usage (kWh)'][10]
print(kwh_2)
# 원하는 결과물 [200, 36, 0]

block_2 = kwh_2 - STEP_LIMITS['기타']
result_2 = np.zeros(block_2.size)

print(block_2)
print(result_2)

236
[ 236   36 -164]
[0. 0. 0.]


In [92]:
kwh_3 = calc.datas['usage (kWh)'][80]
print(kwh_3)
# 원하는 결과물 [200, 200, 94]

block_3 = kwh_3 - STEP_LIMITS['기타']
result_3 = np.zeros(block_3.size)

print(block_3)
print(result_3)

494
[494 294  94]
[0. 0. 0.]


In [ ]:
# [300, 150, 44]